### ISSUE TITLE
Decimal en integer velden software eis 

### ISSUE THREAD

**Issue by ArneBruinse** [nl-digigo/visi#128]
Snelle notitie: Jos wil graag dat er een software eis bij komt dat visi software bij decimal en integer velden, niet alvast een 0 invult, zodat het invullen een bewuste handeling van de gebruiker moet zijn.
Het risico dat je af wilt vangen, is dat als iets vooraf al ingevuld is, dat de gebruiker hier overheen scrollt. Dit heeft weer de consequentie dat je juridisch dispuut kunt krijgen, of de gebruiker bewust "0"   gecommuniceerd heeft, of dat die de "schuld" aan de software kan geven.
Extra testcase: als je een waarde nog even wilt verwijderen als gebruiker moet dat ook kunnen.

De wens is dat dit in de documentatie als een software eis komt en ook in het testprotocol opgenomen wordt.

update 17-12-2021:
jeroen zoekt software richtlijnen document van jos of michon van 2 a4'tjes over bijv reactietermijnen/volgnummers enz..
het idee is om dit niet te verplichten in de standaard

**Comment by tessaderoos** [comment]
Dit kan opgelost worden met softwareleverancier. Geen toevoeging systematiek.
