### ISSUE TITLE
XML Schema definitiebestand niet aanwezig

### ISSUE THREAD

**Issue by redmer** [nl-digigo/visi#142]
In het ondergenoemde bestand, dat volgens bestandsnaam een XSD-definitie van (een onderdeel van) VISI is, is (vermoedelijk) slechts de content van een snelkoppelingsbestand :) 

https://github.com/bimloket/visi/blob/41f2018ef67e5320f9b64076d8c0801257ae9831/1_technische_documentatie/actueel/VISI%201.6%20definitie/_3.xsd#L1

Gewenste oplossing: een correct XSD-bestand.

**Comment by tessaderoos** [comment]
_3.xsd toegevoegd
