### ISSUE TITLE
Twee startberichten voor transactie

### ISSUE THREAD

**Issue by JanaxLooij** [nl-digigo/visi#41]
Twee startberichten voor transactie; 'LastMessage' wanneer de transactie gestart is met een 'FirstMessage'.

Transacties kunnen indien nodig worden ingericht met twee startberichten. Het ene startbericht dient om gekoppeld te worden met een voorgaande transactie. De andere dient om de transactie solitair te kunnen opstarten. Dat het er twee zijn heeft te maken met verschillende elementcondities die van toepassing kunnen zijn. 
Afhankelijk of deze transactie een terugkoppeling heeft, is het vaak nodig om twee verschillende paden (gekoppeld of solitair) te modelleren. Dit omdat de terugkoppelingen verschillen in het geval dit startbericht gekoppeld of solitair was.

#### Attachments
[Toelichting issue 1248.xlsx](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=1248&FileAttachmentId=595)

#### This work item was migrated from CodePlex
CodePlex work item ID: '1248'
Vote count: '1'

**Comment by JanaxLooij** [comment]
[100023@1-4-2014]
(Bruinse)
wat is de vraag? Graag als bijlage een compact raamwerk met de probleemstelling

(Hamilton)
In attachment is een voorbeeld uitgewerkt, dat aangeeft waarom het nodig is om met verschillende startberichten te werken.
In dit voorbeeld is gekozen om geen aparte transacties te maken die hetzelfde beoogen: bijvoorbeeld het leveren van een advies.
Naar verwachting is het dan ook verstandig om afbeeldingen van de workflow in software zich te beperken tot alleen die berichten af te beelden die op basis van de hoofdtransactie kunnen worden gekozen.
Het is dus geen vraag maar een constatering die gevolgen heeft voor met name de afbeelding van workflows in de software. Echter dit probleem is wellicht te voorkomen om naast 'FirstMessage' bij het laatste bericht aan te geven dat hier de transactie stopt 'LastMessage' wanneer de transactie gestart is met een 'FirstMessage'

**Comment by JanaxLooij** [comment]
[UnknownUser@1-4-2014]

**Comment by JanaxLooij** [comment]
[UnknownUser@11-4-2014]

**Comment by JanaxLooij** [comment]
[UnknownUser@11-4-2014]

**Comment by JanaxLooij** [comment]
[UnknownUser@10-7-2015]

**Comment by JanaxLooij** [comment]
[UnknownUser@10-7-2015]

**Comment by JanaxLooij** [comment]
[UnknownUser@10-7-2015]

**Comment by JanaxLooij** [comment]
[UnknownUser@10-7-2015]

**Comment by JanaxLooij** [comment]
[jvgeijlswijk@19-2-2016]
Dit is op 19-02-2016 besproken bij het doornemen van de product backlog van VISI, en Jos heeft de actie op izh genomen om het work item beter te omschrijven. Aanwezig: Ge, Peter, Arne, Paul, Roy, Jos, Jeroen.

**Comment by JanaxLooij** [comment]
[UnknownUser@19-2-2016]

**Comment by JanaxLooij** [comment]
[jvgeijlswijk@19-2-2016]
Work item is teruggezet in de backlog.

**Comment by JanaxLooij** [comment]
[joshamilton@21-2-2016]
Probleem beschrijving:
Na ontvangst van een bericht met hierin een voorstel of uitwerking, kan de behoefte bestaan eerst een adviseur om reactie te vragen om na ontvangst toestemming te vragen aan bijvoorbeeld een projectmanager. Het ontvangen bericht wordt dan een previous van het bericht in de adviestransactie. En ook van toestemmingtransactie. Beide subtransacties hebben dezelfde initiator en een verschillende executor. Het is wenselijk dat het antwoord van de adviestransactie gekoppeld kan worden aan het eerste bericht van de toestemmingtransactie. De gebruiker hoeft dan alleen maar door te klikken. Technisch kan dit, maar dan wordt er een nieuwe transactie opgestart met als initiator de adviseur en niet de executor van de hoofdtransactie. Verzoek is om dit toch mogelijk te maken. 
N.B. je zou overigens een foutbericht moeten ontvangen omdat de initiator van de tweede subtransactie niet de goede is. Maar de praktijk is een andere.

**Comment by JanaxLooij** [comment]
[jvgeijlswijk@8-4-2016]
Prioriteit is ingevuld.

**Comment by JanaxLooij** [comment]
[UnknownUser@8-4-2016]

**Comment by tessaderoos** [comment]
EC/GC 05-02-2024:
Niet duidelijk wat het work item is. Mocht dit nog steeds een probleem zijn, dan graag een nieuw issue met een ingevulde user story template
