### ISSUE TITLE
Praktijkvoorbeelden VISI 2.0

### ISSUE THREAD

**Issue by JanaxLooij** [nl-digigo/visi#59]
N.a.v. VISI Werksessie op 14-04-2017 over DEMO & VISI 2.0...

Openstaande vragen:

Objectenwereld is in DEMO vastgelegd in FactModel. Hoe gaat de informatie over deze objecten gedeeld worden door VISI gebruikers?
Zijn rules in Action model absoluut noodzakelijk?

Hoe laten we stappen automatisch doen, impliciete of automatische stappen? Hoe wordt dit makkelijk configureerbaar?

To Do:

OCD model uitwerken in PSD worstendiagram. Actie Leon.
Uitzoeken hoe data(bank) tot stand komt. Welke data wordt gemuteerd en dient verwerkt in databank? Actie Niek.
Hoe laten we stappen automatisch doen, impliciete of automatische stappen?

#### Attachments
[Mapping VISI1.x op DEMO transacties.docx](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4788&FileAttachmentId=4013)
[e-mail Jeroen van Geijlswijk vrijdag 10 maart 2017 1929.pdf](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4788&FileAttachmentId=4014)
[VISI 2.0 v02.pdf](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4788&FileAttachmentId=4015)
[VISI 2.0 v03.pdf](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4788&FileAttachmentId=4016)
[Technische specificatie VISI 2d.pdf](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4788&FileAttachmentId=4017)
[VISI20 werksessie 20170524.docx](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4788&FileAttachmentId=4018)
[Mapping VISI1.x op DEMO transacties v2.docx](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4788&FileAttachmentId=4019)
[werksessie 20170609.pdf](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4788&FileAttachmentId=4020)
[VISI werksessie III 20170609.docx](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4788&FileAttachmentId=4021)
[e-mail Ronald Bergs.pdf](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4788&FileAttachmentId=4022)

#### This work item was migrated from CodePlex
CodePlex work item ID: '4788'
Vote count: '1'

**Comment by JanaxLooij** [comment]
[LeonvanKervel@14-4-2017]
Openstaande vragen:
1.	Objectenwereld is in DEMO vastgelegd in FactModel. Hoe gaat de informatie over deze objecten gedeeld worden door VISI gebruikers?
2.	Zijn rules in Action model absoluut noodzakelijk?
3.	Hoe laten we stappen automatisch doen, impliciete of automatische stappen? Hoe wordt dit makkelijk configureerbaar?
To Do:
4.	OCD model uitwerken in PSD worstendiagram. Actie Leon.
5.	Uitzoeken hoe data(bank) tot stand komt. Welke data wordt gemuteerd en dient verwerkt in databank? Actie Niek.
6.	Hoe laten we stappen automatisch doen, impliciete of automatische stappen?

**Comment by JanaxLooij** [comment]
[UnknownUser@14-4-2017]

**Comment by JanaxLooij** [comment]
[jvgeijlswijk@14-4-2017]
E-mail met aanvullingen op de functionele specificatie is bijgevoegd.

**Comment by JanaxLooij** [comment]
[UnknownUser@14-4-2017]

**Comment by JanaxLooij** [comment]
[jvgeijlswijk@14-4-2017]
Functionele specificatie v02 is bijgevoegd.

**Comment by JanaxLooij** [comment]
[UnknownUser@14-4-2017]

**Comment by JanaxLooij** [comment]
[UnknownUser@24-5-2017]

**Comment by JanaxLooij** [comment]
[jvgeijlswijk@24-5-2017]
VISI 2.0 v03.pdf

**Comment by JanaxLooij** [comment]
[UnknownUser@24-5-2017]

**Comment by JanaxLooij** [comment]
[jvgeijlswijk@24-5-2017]
Technische specificatie VISI 2d.pdf

**Comment by JanaxLooij** [comment]
[UnknownUser@24-5-2017]

**Comment by JanaxLooij** [comment]
[LeonvanKervel@24-5-2017]
notities werksessie 24-05-2017 bijgevoegd

**Comment by JanaxLooij** [comment]
[UnknownUser@24-5-2017]

**Comment by JanaxLooij** [comment]
[LeonvanKervel@24-5-2017]
Update van mapping VISI1.x op DEMO transacties: suggestie voor PSD 'wijzigingstransacties' opgenomen + enkele notities.

**Comment by JanaxLooij** [comment]
[UnknownUser@2-6-2017]

**Comment by JanaxLooij** [comment]
[niekpluijmert@2-6-2017]
Document ter voorbereiding werksessie 9 juni 2017 toegevoegd

**Comment by JanaxLooij** [comment]
[UnknownUser@9-6-2017]

**Comment by JanaxLooij** [comment]
[LeonvanKervel@9-6-2017]
Werksessie III 09-06-2017

**Comment by JanaxLooij** [comment]
[UnknownUser@12-6-2017]

**Comment by JanaxLooij** [comment]
[niekpluijmert@12-6-2017]
terugkoppeling Ronald Bergs

**Comment by tessaderoos** [comment]
EC/GC 05-02-2024:
"2.0 was hier anders bedoeld dan 'release ná 1.9'. De voorgestelde oplossing in issue over VISI "2.0" wordt niet uitgevoerd."
