### ISSUE TITLE
Machtigingen in VISI

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/visi#69]
Actiehouder gebruikerscommissie: Suzan van der Broek & Henk Wieggers

Betreft: zichtbaarheid van versturing bericht "namens"
Juridische kwestie & discussiepunt over wat moet worden vastgelegd in de VISI standaard, en welke functionaliteit (namelijk: delen van informatie over verstuurd namens) vrij aan te brengen is in de software.

**Comment by ArneBruinse** [comment]
Graag ook in de nieuwe userstory format uitwerken aub.

**Comment by ArneBruinse** [comment]
@ElisabethKloren misschien de wens van Remco Bom die vanmiddag besproken is samen te voegen met dit item?

**Comment by niekpluijmert** [comment]
Het antwoord van de EC, nl. vraag voor verduidelijking, is besproken in de BC en heeft tot het volgende geleid:

In het PSB kun je meerdere personen aanwijzen voor een rol. Een persoon krijgt de berichten in zijn inbox in de software de ander verstuurt dan berichten vanuit diezelfde inbox, tenminste in de software. De ontvanger van het bericht ziet “Piet verstuurt namens Klaas” maar weet niet meer, dat hij in het PSB heeft afgesproken dat beide personen een rol delen en dus beiden berichten kunnen sturen namens die rol. Standpunt expertcommissie: het PSB is tussen beide partijen overeengekomen, dus je ontvangt het bericht van de afgesproken persoon. De vraag is: als de gebruiker “namens” ziet staan, raakt hij dan niet in de war? En is wel duidelijk, dat hij alleen berichten kan krijgen van de personen die zijn vastgelegd in het PSB? De beheercommissie wil hier niet meteen over besluiten.
Besluit: Klein comité (2 gebruikerscommissie, 2 expertcommissie, 1 beheercommissie) bespreken dit. Deelnemers: Frits, Suzan, Niek, Jur

Ik voeg ook het document toe dat bevat:
- beschrijving van de user story
- oorspronkelijke vraag Remco Bom, binnengekomen op de site
- maiwisseling

[20190510-82-Bijlage 3-User Story Machtigingen in VISI v0.1.docx](https://github.com/bimloket/visi/files/5366638/20190510-82-Bijlage.3-User.Story.Machtigingen.in.VISI.v0.1.docx)

**Comment by tessaderoos** [comment]
EC/GC 05-02-2024:
"'Verstuur namens' opgenomen in systematiek"
