### ISSUE TITLE
Documentatie: onduidelijkheid aangaande SOAP communicatie

### ISSUE THREAD

**Issue by edelater** [nl-digigo/visi#80]
> Dit issue is onderdeel van een serie issues waar Future Insight tegenaan liep tijdens implementatie van VISI.

### onduidelijkheid over de SOAP communicatie:
  - namespaces
  - method argumenten
  - wel/niet verplichte headers bij welke methods?
  - hoe zit het precies met MTOM (nog steeds onduidelijk, requireMtom levert foutmeldingen bij de andere leveranciers)
  - eerst bestanden? eerst bericht? hoe zit het met de 'count' property in berichten?
  - number/name/description: wat is de betekenis/het verschil tussen name/description? Documentatie heeft het alleen over 'onderwerp'.
  - soapserverurl
    - zoeken naar de soapgegevens: bleek een standaard naam te hebben (SOAPSERVERURL)
    - wel/geen MTOM protocol? wordt dat genegeerd? (mtomrequired = true geeft fouten).

Uiteindelijk een voorbeeld wsdl gekregen en deze nagebouwd.

**Comment by niekpluijmert** [comment]
Dit punt moet in het bijwerken van de technische documentatie worden opgenomen.

**Comment by ElisabethKloren** [comment]
Aanvullend hierop, ik citeer: "Daarnaast zitten er nog steeds onjuistheden in de documentatie; een simpel voorbeeld: de <Data /> elementen in de soap berichten voor attachments. Het stelt allemaal wellicht niet veel voor, maar het heeft me ooit veel tijd gekost."

**Comment by tessaderoos** [comment]
@MarkMulderTeec2 evt opnemen in documentatie - uitleg SOAP
