### ISSUE TITLE
Implementatie: 'in de praktijk niet gebruikt'

### ISSUE THREAD

**Issue by edelater** [nl-digigo/visi#83]
> Dit issue is onderdeel van een serie issues waar Future Insight tegenaan liep tijdens implementatie van VISI.

### 'in de praktijk niet gebruikt'
  - groupType
  - transactionPhaseType
  - central soap server

  Het zit in de standaard, maar in de documentatie staat zelfs al dat leveranciers het niet ondersteunen. Wat moeten we hier dan mee?
 
In de originele documentatie van de VISI Standaard uit 2003 staat op pagina 80 **GroupType** beschreven en op pagina 81 **TransactionPhaseType**.
[1082_visi_handboek juni 2003.pdf](https://github.com/bimloket/visi/files/4204741/1082_visi_handboek.juni.2003.pdf)

**Comment by ArneBruinse** [comment]
groupType
Deze weet niemand waarom hij er ooit in is gekomen, daarom is hij ook optioneel gemaakt. Voorstel is om het erin te laten. Jos denkt hier in de toekomst nog gebruik van te kunnen maken.

transactionPhaseType
Dit is bedoeld voor de demo transactie fases en wordt ondertussen ingezet voor de DEMO oplegger.

central soap server
Deze is bedoeld dat ieder soap bericht ook op een derde server bewaard wordt, die bijvoorbeeld bij een notaris staat. Mocht de vraag ooit actueel worden, dan is de oplossing deels al beschikbaar.

@edelater kun je genoeg met deze antwoorden?

**Comment by tessaderoos** [comment]
EC/GC 05-02-2024:
#126 opgenomen in VISI 1.7
